### PR TITLE
added screenview logo

### PR DESCRIPTION
**Pull request by KillerQueen-BitesZaDusto**

### CODE REVIEW

**Comment by ahmedsadman** [comment]
In the landing page, make the logo a 'little bit' smaller

**Comment by ahmedsadman** [comment]
And remove this thing, when did it get there??
Capture

**Comment by KillerQueen-BitesZaDusto** [comment]
> And remove this thing, when did it get there??
> Capture

**Review by ahmedsadman — APPROVED** [review]
All good. For the FreePik attribution, we'll create a separate attribution page and list all the attributions there

**Pull request merged**
